### ISSUE TITLE
Maximum function nesting level reached

### ISSUE THREAD

**Issue by unixslayer** [prolic/fpp#137]
To see what may happen, I took `demo/exmaple.fpp` file and run

```
$ bin/fpp example.fpp
```

In return I got

```
PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/unixslayer/projekty/mailservice/vendor/phunkie/phunkie/src/Phunkie/Types/Tuple.php:140
Stack trace:
#0 /home/unixslayer/projekty/mailservice/vendor/phunkie/phunkie/src/Phunkie/Types/Tuple.php(140): substr()
#1 /home/unixslayer/projekty/mailservice/vendor/phunkie/phunkie/src/Phunkie/Types/Tuple.php(133): Phunkie\Types\Tuple->keyFromMember()
#2 /home/unixslayer/projekty/mailservice/vendor/phunkie/phunkie/src/Phunkie/Types/Tuple.php(40): Phunkie\Types\Tuple->includedInMembers()
#3 /home/unixslayer/projekty/mailservice/vendor/phunkie/phunkie/src/Phunkie/Types/Pair.php(24): Phunkie\Types\Tuple->__get()
#4 /home/unixslayer/projekty/mailservice/vendor/prolic/fpp/src/Parser.php(52): Phunkie\Types\Pair->__get()
#5 /home/unixslayer/projekty/mailservice/vendor/prolic/fpp/src/Functions/fpp.php(25): Fpp\Parser->Fpp\{closure}()
#6 /home/unixslayer/projekty/mailservice/vendor/prolic/fpp/src/Parser.php(53): Fpp\flatMap()
#7 /home/unixslayer/p in /home/unixslayer/projekty/mailservice/vendor/phunkie/phunkie/src/Phunkie/Types/Tuple.php on line 140
```

Do I have to do something with my local environment before using FPP or this is (un)known issue?

**Comment by unixslayer** [comment]
same error shows for other demo examples

**Comment by prolic** [comment]
try disabling xdebug or set xdebug.max_nesting_level=2560 (just some higher number).

I might kick out the Tuples, as they have some drawback (as you've noticed), but in general it should work.
