### ISSUE TITLE
Invalid deriving

### ISSUE THREAD

**Issue by Maikel-Koek** [prolic/fpp#30]
Hi @prolic,

The following code worked before:
```
namespace ReachDigital\Subscription\Model\Subscription {
    ...
    data Status = Status\AwaitingFulfillment | Status\Active | Status\Cancelled deriving(Enum);
    ...
}
```

But I just tried to edit our fpp file for some other things, and now the following error shows up:

```
Fatal error: Uncaught Fpp\InvalidDeriving: Invalid deriving on ReachDigital\Subscription\Model\Subscription\Status, deriving Enum expects constructor without any namespace in /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/src/InvalidDeriving.php:58
```

Any ideas?

My full stack trace:
```
php /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/bin/fpp.php /Users/maikelkoek/Sites/vanmoof/src/vendor/reach-digital/magento2-subscriptions/src/Model/Domain.fpp /Users/maikelkoek/Sites/vanmoof/src/vendor/reach-digital/magento2-subscriptions/src/Model/Domain.php

Fatal error: Uncaught Fpp\InvalidDeriving: Invalid deriving on ReachDigital\Subscription\Model\Subscription\Status, deriving Enum expects constructor without any namespace in /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/src/InvalidDeriving.php:58
Stack trace:
#0 /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/src/Deriving/Enum.php(75): Fpp\InvalidDeriving::noConstructorNamespacesAllowed(Object(Fpp\Definition), 'Enum')
#1 /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/src/Definition.php(103): Fpp\Deriving\Enum->checkDefinition(Object(Fpp\Definition))
#2 /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/src/parse.php(562): Fpp\Definition->__construct('ReachDigital\\Su...', 'Status', Array, Array, Array, NULL)
#3 /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/bin/fpp.php(36): Fpp\parse('/Users/maikelko...', Array)
#4 {main}
  thrown in /Users/maikelkoek/Sites/vanmoof/src/vendor/prolic/fpp/src/InvalidDeriving.php on line 58

Process finished with exit code 255
```

**Comment by Maikel-Koek** [comment]
This seems to cause the issues:

https://github.com/prolic/fpp/commit/27801f750c17488e4ac71d61519f4bafffc0ab35#diff-a46a12735ff291b0b7d78722b2550cb4R51

This is recently added. May I ask why the namespace isn't allowed anymore (`Status\AwaitingFulfillment`)?

**Comment by prolic** [comment]
Try this:

`data Status = AwaitingFulfillment | Active | Cancelled deriving(Enum);`

The enum deriving was completely refactored and now support also value mappings (see wiki for examples).

Sorry this change made problems with your code, but that's the way it is using non-stable software :-)

**Comment by Maikel-Koek** [comment]
Ah yes, that seems to be working, I wasn't sure it would since the classes are in another namespace, but it works.

**Comment by prolic** [comment]
There are no more subclasses for enum types, you would need to delete them
manually.
