### ISSUE TITLE
Can't create an event with a single field

### ISSUE THREAD

**Issue by Maikel-Koek** [prolic/fpp#32]
When trying to add an event with a single field, like this:

```
namespace ReachDigital\Subscription\Model\ProductPlan\Event {
...
    data ProductPlanWasDiscontinued = ProductPlanWasDiscontinued {
        \ReachDigital\Subscription\Model\ProductPlan\PlanId $planId,
    } deriving (AggregateChanged);
...
}
```

The following error appears:

```
Fatal error: Uncaught TypeError: Return value of Fpp\Builder\buildPayloadValidation() must be of the type string, boolean returned in /src/vendor/prolic/fpp/src/builder/buildPayloadValidation.php:203
Stack trace:
#0 /src/vendor/prolic/fpp/src/replace.php(28): Fpp\Builder\buildPayloadValidation(Object(Fpp\Definition), Object(Fpp\Constructor), Object(Fpp\DefinitionCollection), '{{payload_valid...')
#1 /src/vendor/prolic/fpp/src/dump.php(47): Fpp\replace('namespace Reach...', Object(Fpp\Definition), Object(Fpp\Constructor), Object(Fpp\DefinitionCollection))
#2 /src/vendor/prolic/fpp/bin/fpp.php(44): Fpp\dump(Object(Fpp\DefinitionCollection), Object(Closure), '\\Fpp\\loadTempla...', '\\Fpp\\replace')
#3 {main}
  thrown in /src/vendor/prolic/fpp/src/builder/buildPayloadValidation.php on line 203

Process finished with exit code 255
```

**Comment by prolic** [comment]
thanks for reporting, it's fixed now and I added another test-case
